### ISSUE TITLE
[Strange Behavior] - Stone Skin Skill

### ISSUE THREAD

**Issue by TensaiKato** [GMBoreas/trocalculator#184]
When selecting Stone Skin level 5, it's not adding the DEFs (need to do research on this) and also when using a physical skill it doesn't calculate the damage.

https://calc.talonro.com/?cawbLbibqabadbCbmabucbapdhaQaQehaajXeaQaaaaaahkaawkeKwXeRbhyVizfjgZfLfafLfaaaaaaikkffaaaabkaaaaaaaepkaaaiMabaaaaEaaaHaHaaa

^ Damage should be superb on that.

![image](https://user-images.githubusercontent.com/39836231/41358328-8a4cd164-6efe-11e8-89f1-a7518c6cf40a.png)

**Comment by kutsuru** [comment]
Normal behaviour for Stone Skin, it does not impact the defense but instead reduces the final damage by 20% x SkillLv. In fact the issue is more related to the MDEF reduction which should not happen. I took the opportunity to fix Magic Mirror which was behaving like Anti Magic, and add a input for Anti Magic.
