### ISSUE TITLE
[Bug] soft DEF

### ISSUE THREAD

**Issue by ghost** [GMBoreas/trocalculator#282]
2 variable exist for soft def: n_A_DEFVIT and n_A_VITDEF,
n_A_DEFVIT is used for display.
n_A_VITDEF is used for battle calculations.
A lot of effects currently only affect one of these, not both.

**Comment by kutsuru** [comment]
Those two variables have a different purpose
n_A_DEFVIT represent the status soft DEF with is computed from VIT
n_A_VITDEF represent the minimum and maximum damage reduction granted by soft DEF

https://github.com/rathena/rathena/blob/master/src/map/battle.cpp#L5180

But I agree that it was misleading and that some status changes should have been applied directly on soft def/n_A_DEFVIT instead of n_A_VITDEF.

With related commit, n_A_DEFVIT was renamed to n_A_DEF2, and n_A_VITDEF remained named that way.
